# ServiceAccount for team-b sample-react-app (Vault Agent K8s auth)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-react-app-backend
  namespace: team-b
  labels:
    app: sample-react-app
    team: team-b
