apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-dev
    app.kubernetes.io/component: frontend
    app.kubernetes.io/owner: ayaan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client
      app.kubernetes.io/instance: client-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: client
        app.kubernetes.io/instance: client-dev
        app.kubernetes.io/component: frontend
        app.kubernetes.io/owner: ayaan
    spec:
      containers:
      - name: client
        image: amitactive2008/client:latest1
        ports:
        - containerPort: 80

