apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: prod
spec:
  template:
    spec:
      containers:
      - name: migration
        image: amitactive2008/api:latest
        resources:
          requests: 
            memory: "258Mi"
            cpu: "101m"
          limits:
            memory: "513Mi"
            cpu: "501m"
