apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "devsecops/db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DB_USERNAME"
            objectAlias: "DB_USERNAME"
          - path: "DB_PASSWORD"
            objectAlias: "DB_PASSWORD"
      - objectName: "devsecops/jwt-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
