# Client Service — team-b
---
apiVersion: v1
kind: Service
metadata:
  name: sample-react-app-client
  namespace: team-b
  labels:
    app: sample-react-app-client
    team: team-b
spec:
  type: ClusterIP
  selector:
    app: sample-react-app-client
  ports:
    - name: http
      port: 80
      targetPort: 80
