apiVersion: v1
kind: Service
metadata:
    name: client-service
    namespace: dev
spec:
  selector:
    app.kubernetes.io/name: client
    app.kubernetes.io/instance: client-dev
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

