apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: team-a
  labels:
    app: sample-react-app-api
    team: team-a
spec:
  type: ClusterIP
  selector:
    app: sample-react-app-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000

