apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYkJWQWI4Qll1YXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01qSXdPVE0yTkRoYUZ3MHpOakEzTVRrd09UUXhORGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN4K3M2TnFweENGL2E3M1I5ZkZ0RTViNXFhVmNBN3dGQ3VRS1dWdXVTaDUxWVlFd21WdmlIU0pxRGEKQnluTi9nbzVKdVpSM1FEeE1mWkFQTC9VN1V2YW5SVFJlQ2sydTRudU8valFPYmVyS2pzNm0yV1lNSy9QRUNLWApiVGU5akpFajRycHI0aDJ0bmVZSUJpOVNpaG5nNTFmVm5ZYXV4akUxSWhtN1cwaGpVei9nczFQUmNQRkdqQVNUCk5wTHgwRjNwTEtQZTJ6NjZJaDJSNVhFZWd2UWR2bTl4YlUvdDdmRC8yVXJicFhYbkUxVXd6V2I1OUdEU0NLbnkKUGJJR21jT2VLSFJQcElzWm5DSFNkL2dSS1lLV25oU2d2Uk5jUkdzVk1SNTFpWUxtK2JPb3p3c3M1UWdkNGxPdwp5Rm5HQmMzNi9jWHVYZHhBMmE1c3ZRSVlac0tMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUTlBxZnBTNmdyQk1kWlFxRk1Gcmo2MUI4WW1EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0VuUytxTUw3dgpzYmxtYk9UckQ0c3Zha1hnTUlZQXAwYXRTSVJsMkFINUVWbzUybjRad013cjZ3ZU1qcTRFeFBDZi9KcGJEVVlDCldXQ1RWeCtsL0J2cjdnZ0todnNiSnRDNHd0Y1N2cnp5eDJSQmlObU9lR2dyeWNWR3IweEVjMmZIMmlhVDlKdEQKc3dFdzE4NjJEZmhkVEF1UlZkTG5sdjZaK0g3WFRIcWtSc2t6Q1A0aWZEeGcxNXVLVlJtNzNGL1NTbURDelNsTAoxSWcwaXdoUW14cnV3emNzZnFuR3QvY2hTZkNQRHMwUVJYeGhxbWppOTRWbi9aR3grck9aenBDYlQvanB0THB1CjQ3ejdqblNjYlArODZJbnVPNFh5WDhubWpCZExKOEVpdXNpWmJNSFJ5ZUNqOTVXY0VGOGNJYWpqOGJtRUNVUXMKQ1ZDdEd4U2tEcUVECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:6443
  name: kind-vault
contexts:
- context:
    cluster: kind-vault
    namespace: default
    user: devops-oidc
  name: devops
- context:
    cluster: kind-vault
    namespace: team-a
    user: team-a-oidc
  name: team-a
- context:
    cluster: kind-vault
    namespace: team-b
    user: team-b-oidc
  name: team-b
current-context: team-a
kind: Config
users:
- name: devops-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: team-a-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: team-b-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
