apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSFVpNmErM2Nna293RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01qQXdOVFE0TXpOYUZ3MHpOakEzTVRjd05UVXpNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURWemM2WnMyaDVHeVRBY1cxazRVY0NtaVhYbXp5YkZyeE1PeUwrSjNEUVlzWWx5emxSN1ZSejRYK3UKL2thSldlK2V1Y0JyNE9CZG9NamdQVG5BTDE5UHFheE1VZmhFNGlLTjBBeGxKeXNhUzhBKzhQaGdsSjVkQXRqZApFVmZubzQ3SThIdWxSTElZYXlMY3FGWmNGbWJaVk1WMDd3c0g2NUQrdFJPSDhxbGdONFpoUGptem5wdWlCMVh4CnhBeklIMHo3c3FvWTZXeHNoZ2x2TC9kaGhVVHgvdHJKWkpCQ0pRaGlsaTQ2VWtsZjhYMTkrdHBlUnh5TnVYM3QKYnBpdWJqNE80RFZhQjJNSDNQak1PU281QzBZd0JZaExnSk5rR0pUcVZRUGlHSzBiVGx5dkcrRGVHYWpOanFocAp0dGlMazBSNktEMzgzc0lSdlBHZXh4VGNCbWd0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZm9UNVNFZDNvSThIUnZjZk82NW10aTJCNGNEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjk3c2tRTFRMWgpEVzN1REZmK1BiNFlVQjNHV3hXb1d3RUdiOXV1M3U3YWN6b3ptV3JEamFteisvY3NzbUNOa2JzMndXQ0U5Z0ZOCnhZMlFmdUJ6SlM3MlArVXBzSEpMdGgvVDFEYUNtQzZRRnBaR010eWl2dnMrTVVMdkM5ajlHajdBWS9qMytGbE8Kc3k4VFJ1c3M2azViSzFOYmVoc0Z0Q2FNZFYrWE54OGhlVXRNV1YwSklDRVVSMUNhZEg3eGNteVJmWlBHZkFxRwp5UThXdDAwRnJQV01HRnFUeGttN0pVN1NoLzhNVGthVkdFNzdWbEUzSnRSbHE0ajBBNjQvMk1UWXordmVkZ05JCklnRGhvbE4xL2JlUWR6S3duQ2JqQ2J6U2NUek9xV0hRdUxIdU84ZEc0WFNuZXY5aTZiQ1hueVJHbDlnSXhYQ1QKRVV2RU90TVRpbm56Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:6443
  name: kind-vault
contexts:
- context:
    cluster: kind-vault
    namespace: default
    user: devops-oidc
  name: devops
- context:
    cluster: kind-vault
    namespace: team-a
    user: team-a-oidc
  name: team-a
- context:
    cluster: kind-vault
    namespace: team-b
    user: team-b-oidc
  name: team-b
current-context: team-a
kind: Config
users:
- name: devops-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: team-a-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: team-b-oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://keycloak.kind.local/realms/kind
      - --oidc-client-id=kubernetes
      - --oidc-auth-request-extra-params=prompt=login
      - --certificate-authority=/Users/amit.kumar1/Desktop/study/vault-keycloak-k8s-platform/05-k8s-oidc-with-keycloak/keycloak-local-ca.crt
      command: kubectl
      env:
      - name: GODEBUG
        value: netdns=go
      interactiveMode: IfAvailable
      provideClusterInfo: false
