apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-properties
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
data:
  nexus.properties: |
    application-host=0.0.0.0
    application-port={{ .Values.service.port }}
    nexus-context-path=/
    nexus.security.oauth2.enabled=true
    nexus.jwt.enabled=true

