apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

