apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team-a-webapp
  namespace: {{ include "webapp.namespace" . }}
  labels:
    app: team-a-webapp
    {{- include "webapp.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: webapp-backend
                port:
                  number: {{ .Values.backend.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webapp-frontend
                port:
                  number: 80
