#!/usr/bin/env bash
# ============================================================
# setup.sh — Vault ↔ Keycloak OIDC integration
#
# What this does:
#   1. Patches CoreDNS so Vault pods can resolve keycloak.local
#      (Vault's token exchange call must reach Keycloak internally)
#   2. Creates a confidential OIDC client "vault" in the kind realm
#      with a groups claim mapper (full path: /devops, /team-a, /team-b)
#   3. Enables KV v2 secret engine at path "secret/"
#   4. Writes Vault policies (devops / team-a / team-b)
#   5. Enables and configures the OIDC auth method pointing at Keycloak
#   6. Creates an OIDC role "default" that reads the "groups" JWT claim
#   7. Creates Vault external identity groups + OIDC group aliases so
#      Keycloak group membership drives Vault policy assignment
#   8. Seeds sample secrets for each team to verify access
#
# Access matrix after setup:
#   devops  group → devops-policy  → ALL paths  (*)
#   team-a  group → team-a-policy  → secret/data/team-a/*
#   team-b  group → team-b-policy  → secret/data/team-b/*
#
# Usage:
#   cd keycloak/vault-integration/
#   chmod +x setup.sh
#   ./setup.sh
#
# Requires: kubectl, python3
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${SCRIPT_DIR}/../../vault"

# ── Configuration ──────────────────────────────────────────────
ROOT_TOKEN=$(python3 -c "
import json
with open('${DEPLOY_DIR}/cluster-keys.json') as f:
    print(json.load(f)['root_token'])
")
VAULT_NS="vault"
KC_NS="keycloak"
KC_REALM="kind"
KC_ADMIN_PASS="Admin@Keycloak2024!"
KC_EXTERNAL_URL="https://keycloak.local"
VAULT_EXTERNAL_URL="https://vault-webui.local"
OIDC_CLIENT_ID="vault"
OIDC_CLIENT_SECRET="Vault@Keycloak2024!"
# CA cert for Keycloak's self-signed TLS (generated by keycloak/k8s-oidc/setup.sh)
OIDC_CA_CERT_FILE="${SCRIPT_DIR}/../k8s-oidc/keycloak-local-ca.crt"
# vault-active service — always points to the active Vault node
VAULT_ACTIVE_ADDR="http://vault-active.vault.svc.cluster.local:8200"

# ── Helpers ────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
section() { echo -e "\n${GREEN}===== $* =====${NC}"; }

# ── Step 0: Prereqs ─────────────────────────────────────────────
section "Step 0 — Checking prerequisites"
for cmd in kubectl python3; do
  command -v "$cmd" &>/dev/null || { error "$cmd not found"; exit 1; }
  info "$cmd → $(command -v "$cmd")"
done
kubectl cluster-info &>/dev/null || { error "No cluster found. Is kind running?"; exit 1; }
info "Cluster : $(kubectl config current-context)"
info "Vault NS: $VAULT_NS  |  Keycloak NS: $KC_NS"

# ── Step 1: CoreDNS patch ───────────────────────────────────────
# Vault pods are in-cluster and cannot resolve "keycloak.local" (host /etc/hosts
# is not visible inside pods). We inject a hosts entry into CoreDNS so that
# http://keycloak.local resolves to Keycloak's ClusterIP from any pod.
section "Step 1 — Patching CoreDNS to resolve keycloak.local inside the cluster"

# Vault pods need to reach https://keycloak.local. CoreDNS must resolve
# keycloak.local to the nginx ingress ClusterIP (not the Keycloak ClusterIP),
# because only nginx handles HTTPS (TLS termination on port 443).
NGINX_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.clusterIP}')
info "nginx ingress ClusterIP: $NGINX_IP  (handles HTTPS for keycloak.local)"

# If keycloak.local is already in CoreDNS but points to the old Keycloak ClusterIP
# (not nginx), update it so Vault pods reach the HTTPS-capable nginx ingress.
CURRENT_CORE_ENTRY=$(kubectl get configmap coredns -n kube-system -o jsonpath='{.data.Corefile}' 2>/dev/null | grep "keycloak.local" || true)
if echo "$CURRENT_CORE_ENTRY" | grep -q "$NGINX_IP"; then
  warn "CoreDNS already has keycloak.local → $NGINX_IP — skipping patch"
else
  info "Writing CoreDNS ConfigMap with keycloak.local → $NGINX_IP (nginx, HTTPS)..."

  # Write the full Corefile using kubectl apply (safe, no variable-in-heredoc issues).
  # This is the standard kind CoreDNS config with an added hosts block.
  kubectl apply -f - << YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        hosts {
           ${NGINX_IP} keycloak.local
           fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
YAML

  info "CoreDNS ConfigMap applied. Restarting CoreDNS..."
  kubectl rollout restart deployment/coredns -n kube-system
  kubectl rollout status deployment/coredns -n kube-system --timeout=120s
  info "CoreDNS restarted. Waiting 5 s for DNS propagation..."
  sleep 5
fi

# Quick smoke-test: can a vault pod resolve keycloak.local?
RESOLVE_RESULT=$(kubectl exec -n "$VAULT_NS" vault-0 -- \
  sh -c "nslookup keycloak.local 2>&1 || getent hosts keycloak.local 2>&1 || echo UNRESOLVED")
if echo "$RESOLVE_RESULT" | grep -qiE "$NGINX_IP|address"; then
  info "DNS check passed — keycloak.local resolves from vault-0 ✓"
else
  warn "DNS check inconclusive ($RESOLVE_RESULT). Proceeding anyway..."
fi

# ── Step 2: Keycloak OIDC client ────────────────────────────────
section "Step 2 — Creating Keycloak OIDC client 'vault' in realm '$KC_REALM'"

KC_POD=$(kubectl get pod -n "$KC_NS" -l app=keycloak \
  -o jsonpath='{.items[0].metadata.name}')
info "Keycloak pod: $KC_POD"

# Authenticate kcadm
kubectl exec -n "$KC_NS" "$KC_POD" -- \
  /opt/keycloak/bin/kcadm.sh config credentials \
  --server http://localhost:8080 --realm master \
  --user admin --password "$KC_ADMIN_PASS"

# Check if client already exists
CLIENT_EXISTS=$(kubectl exec -n "$KC_NS" "$KC_POD" -- \
  /opt/keycloak/bin/kcadm.sh get clients -r "$KC_REALM" \
  --fields clientId 2>/dev/null | grep -c '"vault"' || true)

if [ "$CLIENT_EXISTS" -gt 0 ]; then
  warn "Keycloak client 'vault' already exists — skipping creation"
else
  info "Creating confidential OIDC client 'vault'..."
  kubectl exec -n "$KC_NS" "$KC_POD" -- \
    /opt/keycloak/bin/kcadm.sh create clients -r "$KC_REALM" \
    -s clientId="${OIDC_CLIENT_ID}" \
    -s enabled=true \
    -s protocol=openid-connect \
    -s publicClient=false \
    -s standardFlowEnabled=true \
    -s implicitFlowEnabled=false \
    -s directAccessGrantsEnabled=false \
    -s serviceAccountsEnabled=false \
    -s secret="${OIDC_CLIENT_SECRET}" \
    -s "redirectUris=[\"${VAULT_EXTERNAL_URL}/ui/vault/auth/oidc/oidc/callback\",\"http://localhost:8250/oidc/callback\"]" \
    -s "webOrigins=[\"${VAULT_EXTERNAL_URL}\"]"
  info "Client 'vault' created."
fi

# Retrieve client UUID
CLIENT_UUID=$(kubectl exec -n "$KC_NS" "$KC_POD" -- \
  /opt/keycloak/bin/kcadm.sh get clients -r "$KC_REALM" \
  --fields id,clientId 2>/dev/null \
  | grep -B1 '"vault"' | grep '"id"' | head -1 | awk -F'"' '{print $4}')
info "Client UUID: $CLIENT_UUID"

# Always sync the redirect URIs — covers both fresh creates and re-runs where
# the client already existed with stale (http-only) redirect URIs.
info "Syncing redirectUris and webOrigins on client 'vault'..."
kubectl exec -n "$KC_NS" "$KC_POD" -- \
  /opt/keycloak/bin/kcadm.sh update "clients/${CLIENT_UUID}" -r "$KC_REALM" \
  -s "redirectUris=[\"${VAULT_EXTERNAL_URL}/ui/vault/auth/oidc/oidc/callback\",\"http://vault-webui.local/ui/vault/auth/oidc/oidc/callback\",\"https://localhost:8250/oidc/callback\",\"http://localhost:8250/oidc/callback\"]" \
  -s "webOrigins=[\"${VAULT_EXTERNAL_URL}\",\"http://vault-webui.local\"]"
info "redirectUris updated."

# Add groups claim mapper (full path: /devops, /team-a, /team-b in the JWT)
MAPPER_COUNT=$(kubectl exec -n "$KC_NS" "$KC_POD" -- \
  /opt/keycloak/bin/kcadm.sh get \
  "clients/${CLIENT_UUID}/protocol-mappers/models" \
  -r "$KC_REALM" 2>/dev/null | grep -c '"groups"' || true)

if [ "$MAPPER_COUNT" -gt 0 ]; then
  warn "Groups mapper already exists on client 'vault' — skipping"
else
  info "Adding group-membership (full path) mapper to 'vault' client..."

  # Write mapper JSON to a temp file in the pod and apply it
  kubectl exec -n "$KC_NS" "$KC_POD" -- sh -c '
cat > /tmp/mapper.json << EOF
{
  "name": "groups",
  "protocol": "openid-connect",
  "protocolMapper": "oidc-group-membership-mapper",
  "config": {
    "full.path": "true",
    "id.token.claim": "true",
    "access.token.claim": "true",
    "userinfo.token.claim": "true",
    "claim.name": "groups",
    "multivalued": "true"
  }
}
EOF
'

  kubectl exec -n "$KC_NS" "$KC_POD" -- \
    /opt/keycloak/bin/kcadm.sh create \
    "clients/${CLIENT_UUID}/protocol-mappers/models" \
    -r "$KC_REALM" -f /tmp/mapper.json

  kubectl exec -n "$KC_NS" "$KC_POD" -- rm -f /tmp/mapper.json
  info "Groups mapper added. JWT will include 'groups': [\"/devops\", ...]"
fi

# ── Step 3: KV v2 secret engine ─────────────────────────────────
section "Step 3 — Enabling KV v2 at 'secret/'"

kubectl exec -n "$VAULT_NS" vault-0 -- sh -c "
  export VAULT_ADDR=${VAULT_ACTIVE_ADDR}
  export VAULT_TOKEN=${ROOT_TOKEN}
  vault secrets enable -path=secret kv-v2 2>/dev/null \
    && echo 'KV v2 enabled at secret/' \
    || echo 'KV v2 at secret/ already enabled'
"

# ── Step 4: Vault policies ──────────────────────────────────────
section "Step 4 — Writing Vault policies"

# Copy HCL policy files into the pod then write them
for TEAM in devops team-a team-b; do
  info "Writing policy: ${TEAM}-policy"
  kubectl cp "${SCRIPT_DIR}/policies/${TEAM}.hcl" \
    "${VAULT_NS}/vault-0:/tmp/${TEAM}.hcl"
  kubectl exec -n "$VAULT_NS" vault-0 -- sh -c "
    export VAULT_ADDR=${VAULT_ACTIVE_ADDR}
    export VAULT_TOKEN=${ROOT_TOKEN}
    vault policy write ${TEAM}-policy /tmp/${TEAM}.hcl
    rm /tmp/${TEAM}.hcl
  "
done

# ── Step 5: OIDC auth method ────────────────────────────────────
section "Step 5 — Enabling and configuring OIDC auth method"

# Build the OIDC config as a JSON file locally so the multiline CA cert PEM is
# correctly JSON-encoded (inline shell expansion breaks on cert newlines).
OIDC_CONFIG_JSON=$(mktemp /tmp/vault-oidc-config.XXXXXX.json)
python3 - << PYEOF
import json
ca = open("${OIDC_CA_CERT_FILE}").read() if __import__('os').path.exists("${OIDC_CA_CERT_FILE}") else ""
cfg = {
    "oidc_discovery_url":    "${KC_EXTERNAL_URL}/realms/${KC_REALM}",
    "oidc_discovery_ca_pem": ca,
    "oidc_client_id":        "${OIDC_CLIENT_ID}",
    "oidc_client_secret":    "${OIDC_CLIENT_SECRET}",
    "default_role":          "default"
}
with open("${OIDC_CONFIG_JSON}", "w") as f:
    json.dump(cfg, f)
PYEOF
info "OIDC config JSON built (CA cert lines: $(python3 -c "import json; d=json.load(open('${OIDC_CONFIG_JSON}')); print(d['oidc_discovery_ca_pem'].count(chr(10)))"))"

kubectl exec -n "$VAULT_NS" vault-0 -- sh -c "
  export VAULT_ADDR=${VAULT_ACTIVE_ADDR}
  export VAULT_TOKEN=${ROOT_TOKEN}
  vault auth enable oidc 2>/dev/null \
    && echo 'OIDC auth method enabled' \
    || echo 'OIDC auth method already enabled'
"

# Copy the JSON config into the pod and apply it with @file (safe multiline handling)
kubectl cp "${OIDC_CONFIG_JSON}" "${VAULT_NS}/vault-0:/tmp/vault-oidc-config.json"
kubectl exec -n "$VAULT_NS" vault-0 -- sh -c "
  export VAULT_ADDR=${VAULT_ACTIVE_ADDR}
  export VAULT_TOKEN=${ROOT_TOKEN}
  vault write auth/oidc/config @/tmp/vault-oidc-config.json
  rm /tmp/vault-oidc-config.json
"
rm -f "${OIDC_CONFIG_JSON}"
info "OIDC auth configured → ${KC_EXTERNAL_URL}/realms/${KC_REALM}"

# ── Step 6: OIDC role ───────────────────────────────────────────
section "Step 6 — Creating OIDC role 'default'"
# This role:
#   • extracts the user subject from the 'sub' claim
#   • reads group membership from the 'groups' claim (set by Keycloak mapper)
#   • grants only the base 'default' policy; group-specific policies are
#     attached via the external group aliases created in the next step

kubectl exec -n "$VAULT_NS" vault-0 -- sh -c '
  export VAULT_ADDR='"${VAULT_ACTIVE_ADDR}"'
  export VAULT_TOKEN='"${ROOT_TOKEN}"'

  cat > /tmp/oidc-role.json << EOF
{
  "bound_audiences": ["'"${OIDC_CLIENT_ID}"'"],
  "allowed_redirect_uris": [
    "'"${VAULT_EXTERNAL_URL}"'/ui/vault/auth/oidc/oidc/callback",
    "https://vault-webui.local/ui/vault/auth/oidc/oidc/callback",
    "http://localhost:8250/oidc/callback",
    "https://localhost:8250/oidc/callback"
  ],
  "user_claim": "sub",
  "groups_claim": "groups",
  "token_ttl": "1h",
  "token_max_ttl": "24h",
  "token_policies": ["default"]
}
EOF

  vault write auth/oidc/role/default @/tmp/oidc-role.json
  rm /tmp/oidc-role.json
  echo "OIDC role default written"
'

# ── Step 7: External groups + group aliases ─────────────────────
# An external group in Vault identity maps to a group in an external auth system.
# A group alias links the JWT group name (e.g. "/devops") to the Vault group so
# that when the OIDC token arrives with "groups":["/devops"], Vault automatically
# assigns the devops-policy to the identity.
section "Step 7 — Creating external identity groups and OIDC group aliases"

kubectl exec -n "$VAULT_NS" vault-0 -- sh -c '
  export VAULT_ADDR='"${VAULT_ACTIVE_ADDR}"'
  export VAULT_TOKEN='"${ROOT_TOKEN}"'

  # Get the OIDC auth mount accessor (needed for group aliases)
  OIDC_ACCESSOR=$(vault auth list | awk "/^oidc\// {print \$3}")
  echo "OIDC accessor: $OIDC_ACCESSOR"

  # ── devops: full admin ──────────────────────────────────────
  DEVOPS_ID=$(vault write -field=id identity/group \
    name=devops type=external policies=devops-policy \
    metadata=description="DevOps engineers — full Vault admin")
  vault write identity/group-alias \
    name="/devops" \
    mount_accessor="$OIDC_ACCESSOR" \
    canonical_id="$DEVOPS_ID"
  echo "Group devops → devops-policy (alias: /devops)"

  # ── team-a: scoped to secret/data/team-a/* ─────────────────
  TEAM_A_ID=$(vault write -field=id identity/group \
    name=team-a type=external policies=team-a-policy \
    metadata=description="Team A — scoped to secret/data/team-a/*")
  vault write identity/group-alias \
    name="/team-a" \
    mount_accessor="$OIDC_ACCESSOR" \
    canonical_id="$TEAM_A_ID"
  echo "Group team-a → team-a-policy (alias: /team-a)"

  # ── team-b: scoped to secret/data/team-b/* ─────────────────
  TEAM_B_ID=$(vault write -field=id identity/group \
    name=team-b type=external policies=team-b-policy \
    metadata=description="Team B — scoped to secret/data/team-b/*")
  vault write identity/group-alias \
    name="/team-b" \
    mount_accessor="$OIDC_ACCESSOR" \
    canonical_id="$TEAM_B_ID"
  echo "Group team-b → team-b-policy (alias: /team-b)"
'

# ── Step 8: Seed sample secrets ─────────────────────────────────
section "Step 8 — Seeding sample secrets for each team"

kubectl exec -n "$VAULT_NS" vault-0 -- sh -c "
  export VAULT_ADDR=${VAULT_ACTIVE_ADDR}
  export VAULT_TOKEN=${ROOT_TOKEN}

  vault kv put secret/team-a/config  app=team-a-service  env=kind  owner=team-a
  vault kv put secret/team-a/db      host=db.team-a      port=5432 password=changeme
  vault kv put secret/team-b/config  app=team-b-service  env=kind  owner=team-b
  vault kv put secret/team-b/db      host=db.team-b      port=5432 password=changeme
  vault kv put secret/devops/cluster name=kind-vault     region=local nodes=4
  echo 'Sample secrets seeded'
"

# ── Done ────────────────────────────────────────────────────────
section "Setup complete!"

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        Vault ↔ Keycloak OIDC Integration Summary            ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Vault UI    : http://vault-webui.local                     ║"
echo "║  Login method: OIDC  (select from dropdown)                 ║"
echo "║  Role        : default                                      ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Group       Policy          Allowed Paths                  ║"
echo "║  ─────────── ─────────────── ──────────────────────────     ║"
echo "║  devops    → devops-policy → ALL paths  (*)                 ║"
echo "║  team-a    → team-a-policy → secret/data/team-a/*           ║"
echo "║  team-b    → team-b-policy → secret/data/team-b/*           ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Test users  (Keycloak password: password)                  ║"
echo "║   devops-user-1 / devops-user-2  → full admin               ║"
echo "║   team-a-user-1 / team-a-user-2  → secret/data/team-a/*     ║"
echo "║   team-b-user-1 / team-b-user-2  → secret/data/team-b/*     ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  Seeded secrets:                                            ║"
echo "║   secret/team-a/config  secret/team-a/db                   ║"
echo "║   secret/team-b/config  secret/team-b/db                   ║"
echo "║   secret/devops/cluster                                     ║"
echo "╠══════════════════════════════════════════════════════════════╣"
echo "║  CLI login:                                                 ║"
echo "║   vault login -method=oidc \\                                ║"
echo "║     -address=http://vault-webui.local role=default          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
