apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: dev
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 300

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: migration
        image: amitactive2008/api:latest
        imagePullPolicy: Always

        command: ["node", "scripts/migrate.js"]

        envFrom:
        - secretRef:
            name: db-secrets
        - configMapRef:
            name: db-config

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
