ingressClass:  
  enabled: true
  isDefaultClass: true

providers:
  kubernetesIngress:
    enabled: true

api:
  dashboard: false

logs:
  general:
    level: INFO

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: false

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true 

