# ServiceAccount for the ingress controller pod
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ingress-nginx
  namespace: {{ include "ingress-nginx.namespace" . }}
  labels:
    {{- include "ingress-nginx.controller.labels" . | nindent 4 }}
---
{{- if .Values.admissionWebhooks.enabled }}
# ServiceAccount for the admission-webhook Jobs
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: ingress-nginx-admission
  namespace: {{ include "ingress-nginx.namespace" . }}
  labels:
    {{- include "ingress-nginx.admission.labels" . | nindent 4 }}
{{- end }}
