apiVersion: v1
kind: Pod
metadata:
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/role: "jenkins-cd-external"
    vault.hashicorp.com/agent-inject-secret-kubeconfig: "secret/data/devops/jenkins/clusters/external"
    vault.hashicorp.com/agent-inject-template-kubeconfig: |
      {{- with secret "secret/data/devops/jenkins/clusters/external" -}}
      {{ .Data.data.kubeconfig }}
      {{- end }}
spec:
  serviceAccountName: jenkins-cd-external
  securityContext:
    fsGroup: 1000

  volumes:
    - name: workspace-volume
      emptyDir: {}

  containers:
    - name: jnlp
      image: jenkins/inbound-agent
      args:
        - "$(JENKINS_SECRET)"
        - "$(JENKINS_NAME)"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["cat"]
      tty: true
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
