apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-cd-team-b

  volumes:
    - name: workspace-volume
      emptyDir: {}

  containers:
    - name: jnlp
      image: jenkins/inbound-agent
      args:
        - "$(JENKINS_SECRET)"
        - "$(JENKINS_NAME)"
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: kubectl
      image: bitnami/kubectl:latest
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: zap
      image: zaproxy/zap-stable:latest
      imagePullPolicy: IfNotPresent
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: workspace-volume
          mountPath: /zap/wrk
